import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import FuncFormatter

# 1. Setup Data Column Names
column_names = [
    'N', 
    'Linear_1', 'Linear_N8', 'Linear_N4', 'Linear_N2',
    'Binary_1', 'Binary_N8', 'Binary_N4', 'Binary_N2',
    'Jump_1', 'Jump_N8', 'Jump_N4', 'Jump_N2'
]

# 2. Load Data
try:
    # Reads the CSV (skips the first 2 header lines generated by main.cpp)
    df = pd.read_csv('farm_results.csv', delimiter=';', skiprows=2, 
                     header=None, names=column_names)
except FileNotFoundError:
    print("Error: 'farm_results.csv' not found. Run main.cpp first.")
    exit()

# Ensure numeric conversion
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')


# 3. Define Custom Formatter for X-Axis (1024 -> 2^10)
def format_func(value, tick_number):
    if value <= 0: return ""
    # Calculate log2 to get the exponent
    exp = np.log2(value)
    # Return formatted string like 2^10
    return r'$2^{{{:.0f}}}$'.format(exp)

# 4. Create Plots
fig, axes = plt.subplots(1, 3, figsize=(18, 6), sharey=False)

labels = ['K=1', 'K=N/8', 'K=N/4', 'K=N/2']

# Helper to apply common styles
def setup_axis(ax, title, is_first=False):
    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xlabel('N (Sheep Count)', fontsize=10)
    if is_first:
        ax.set_ylabel('Time (ms)', fontsize=10)
    
    # CRITICAL: Log Scale Base 2
    ax.set_xscale('log', base=2)
    
    # CRITICAL: Force ticks for EVERY N value in the data (no skipping)
    ax.set_xticks(df['N'])
    
    # Format labels as 2^x
    ax.xaxis.set_major_formatter(FuncFormatter(format_func))
    
    # Optional: Rotate labels if they overlap
    # ax.tick_params(axis='x', rotation=45) 
    
    ax.grid(True, which="major", linestyle='-', alpha=0.5)
    ax.grid(True, which="minor", linestyle='--', alpha=0.2)
    ax.legend()

# --- Plot 1: Linear Search ---
axes[0].plot(df['N'], df['Linear_1'], marker='o', label=labels[0])
axes[0].plot(df['N'], df['Linear_N8'], marker='s', label=labels[1])
axes[0].plot(df['N'], df['Linear_N4'], marker='^', label=labels[2])
axes[0].plot(df['N'], df['Linear_N2'], marker='d', label=labels[3])
setup_axis(axes[0], 'Linear Search', is_first=True)

# --- Plot 2: Binary Search ---
axes[1].plot(df['N'], df['Binary_1'], marker='o', label=labels[0])
axes[1].plot(df['N'], df['Binary_N8'], marker='s', label=labels[1])
axes[1].plot(df['N'], df['Binary_N4'], marker='^', label=labels[2])
axes[1].plot(df['N'], df['Binary_N2'], marker='d', label=labels[3])
setup_axis(axes[1], 'Binary Search')

# --- Plot 3: Jump Search ---
axes[2].plot(df['N'], df['Jump_1'], marker='o', label=labels[0])
axes[2].plot(df['N'], df['Jump_N8'], marker='s', label=labels[1])
axes[2].plot(df['N'], df['Jump_N4'], marker='^', label=labels[2])
axes[2].plot(df['N'], df['Jump_N2'], marker='d', label=labels[3])
setup_axis(axes[2], 'Jump Search')

plt.suptitle('Runtime Performance (Log Scale X-Axis)', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) 

plt.show()